site_name: Basalt
site_url: https://stevepelhan.gitlab.io/basalt
site_dir: public
docs_dir: ./basalt

theme:
  name: material
  palette:
    scheme: slate

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
    permalink: true
    
plugins:
  - search
  - roamlinks
